### ISSUE TITLE
p.173 サンプルコードの誤植

### ISSUE THREAD

**Issue by oohira** [oreilly-japan/programming-typescript-ja#5]
p.173: 7章「7.4 Option型」のflattenのサンプルコードで閉じ括弧の位置に誤りがありそうです。

```ts
flatten(ask())     // ← 閉じ括弧が1つ余分
    .map(parse))
    .map(date => date.toISOString())
    .forEach(...)
```

**Comment by kimamula** [comment]
ご指摘ありがとうございます！
https://github.com/oreilly-japan/programming-typescript-ja/wiki/errata#%E7%AC%AC3%E5%88%B7%E3%81%BE%E3%81%A7 に反映いたしました。
